package heu;

import java.util.ArrayList;
import java.util.PriorityQueue;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Main extends javax.swing.JFrame {

    public Main() {
        initComponents();
        this.setTitle("Hospital Escuela Universitario");
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Administracion = new javax.swing.JDialog();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        Mapa = new javax.swing.JDialog();
        Emergencias = new javax.swing.JDialog();
        Complejos = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        t_nombrehospitales = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        a_Direccion = new javax.swing.JTextArea();
        Sp_paramedicos = new javax.swing.JSpinner();
        Sp_ambulancias = new javax.swing.JSpinner();
        Cb_rankingHospitales = new javax.swing.JComboBox();
        jButton8 = new javax.swing.JButton();
        Paramedicos = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        t_nombreParamedico = new javax.swing.JTextField();
        t_id = new javax.swing.JTextField();
        Cb_rankingParamedicos = new javax.swing.JComboBox();
        Cb_hospitales = new javax.swing.JComboBox();
        jButton9 = new javax.swing.JButton();
        Sp_edad = new javax.swing.JSpinner();
        Ambulancias = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        t_placa = new javax.swing.JTextField();
        t_ano = new javax.swing.JTextField();
        t_velocidad = new javax.swing.JTextField();
        Cb_ambulancias = new javax.swing.JComboBox();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        ComplejosListar = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_complejos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        Eliminar_complejos = new javax.swing.JMenuItem();
        AmbulanciaListar = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla_ambulancias = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        Reasignacion = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cb_reParamedicos = new javax.swing.JComboBox();
        cb_reComplejos1 = new javax.swing.JComboBox();
        jButton13 = new javax.swing.JButton();
        cb_reAmbulancias = new javax.swing.JComboBox();
        cb_reComplejos2 = new javax.swing.JComboBox();
        jButton14 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton4.setText("Complejos Hospitalarios");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Paramedicos");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("Ambulancias");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton10.setText("Reasignacion");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AdministracionLayout = new javax.swing.GroupLayout(Administracion.getContentPane());
        Administracion.getContentPane().setLayout(AdministracionLayout);
        AdministracionLayout.setHorizontalGroup(
            AdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdministracionLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(AdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(AdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );
        AdministracionLayout.setVerticalGroup(
            AdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdministracionLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(AdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(AdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout MapaLayout = new javax.swing.GroupLayout(Mapa.getContentPane());
        Mapa.getContentPane().setLayout(MapaLayout);
        MapaLayout.setHorizontalGroup(
            MapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        MapaLayout.setVerticalGroup(
            MapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout EmergenciasLayout = new javax.swing.GroupLayout(Emergencias.getContentPane());
        Emergencias.getContentPane().setLayout(EmergenciasLayout);
        EmergenciasLayout.setHorizontalGroup(
            EmergenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        EmergenciasLayout.setVerticalGroup(
            EmergenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Complejos Hospitalarios");

        jLabel2.setText("Nombre");

        jLabel3.setText("Direccion");

        jLabel4.setText("Maximo de paramedicos");

        jLabel5.setText("Maximo de ambulancias");

        jLabel6.setText("Ranking");

        jButton7.setText("Agregar");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        a_Direccion.setColumns(20);
        a_Direccion.setRows(5);
        jScrollPane1.setViewportView(a_Direccion);

        Sp_paramedicos.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        Sp_ambulancias.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        Cb_rankingHospitales.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));

        jButton8.setText("Listar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ComplejosLayout = new javax.swing.GroupLayout(Complejos.getContentPane());
        Complejos.getContentPane().setLayout(ComplejosLayout);
        ComplejosLayout.setHorizontalGroup(
            ComplejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComplejosLayout.createSequentialGroup()
                .addGroup(ComplejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComplejosLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(ComplejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ComplejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ComplejosLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ComplejosLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(t_nombrehospitales, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel4)
                                .addComponent(jLabel6))
                            .addGroup(ComplejosLayout.createSequentialGroup()
                                .addGroup(ComplejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(ComplejosLayout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addGroup(ComplejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Cb_rankingHospitales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(ComplejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Sp_paramedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Sp_ambulancias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton8)
                                .addGap(47, 47, 47))))
                    .addGroup(ComplejosLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jButton7))
                    .addGroup(ComplejosLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        ComplejosLayout.setVerticalGroup(
            ComplejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComplejosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(ComplejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t_nombrehospitales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ComplejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComplejosLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3))
                    .addGroup(ComplejosLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ComplejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Sp_paramedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(ComplejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Sp_ambulancias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addGroup(ComplejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Cb_rankingHospitales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jButton7)
                .addGap(28, 28, 28))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Paramedicos");

        jLabel9.setText("Nombre");

        jLabel10.setText("Edad");

        jLabel11.setText("ID");

        jLabel12.setText("Ranking");

        jLabel13.setText("Complejo");

        Cb_rankingParamedicos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));

        jButton9.setText("Agregar");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        Sp_edad.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        javax.swing.GroupLayout ParamedicosLayout = new javax.swing.GroupLayout(Paramedicos.getContentPane());
        Paramedicos.getContentPane().setLayout(ParamedicosLayout);
        ParamedicosLayout.setHorizontalGroup(
            ParamedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ParamedicosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(168, 168, 168))
            .addGroup(ParamedicosLayout.createSequentialGroup()
                .addGroup(ParamedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ParamedicosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(ParamedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(ParamedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cb_rankingParamedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_nombreParamedico, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cb_hospitales, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 60, Short.MAX_VALUE))
                    .addGroup(ParamedicosLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jButton9)))
                .addGap(57, 57, 57))
        );
        ParamedicosLayout.setVerticalGroup(
            ParamedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParamedicosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addGap(36, 36, 36)
                .addGroup(ParamedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(t_nombreParamedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(ParamedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(ParamedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(ParamedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(Cb_rankingParamedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(ParamedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Cb_hospitales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton9)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel14.setText("N. de Placa");

        jLabel15.setText("Año");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Ambulancia");

        jLabel17.setText("Velocidad");

        jLabel18.setText("Complejo");

        jButton11.setText("Agregar");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        jButton12.setText("Listar");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        jLabel19.setText("Km/h");

        javax.swing.GroupLayout AmbulanciasLayout = new javax.swing.GroupLayout(Ambulancias.getContentPane());
        Ambulancias.getContentPane().setLayout(AmbulanciasLayout);
        AmbulanciasLayout.setHorizontalGroup(
            AmbulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AmbulanciasLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(AmbulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addGroup(AmbulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel18)
                        .addComponent(jLabel17)))
                .addGap(18, 18, 18)
                .addGroup(AmbulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t_placa)
                    .addComponent(t_ano)
                    .addComponent(Cb_ambulancias, 0, 206, Short.MAX_VALUE)
                    .addGroup(AmbulanciasLayout.createSequentialGroup()
                        .addComponent(t_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(AmbulanciasLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AmbulanciasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(130, 130, 130))
        );
        AmbulanciasLayout.setVerticalGroup(
            AmbulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AmbulanciasLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel16)
                .addGap(32, 32, 32)
                .addGroup(AmbulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(t_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AmbulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(t_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(AmbulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(t_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(21, 21, 21)
                .addGroup(AmbulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(Cb_ambulancias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(AmbulanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        tabla_complejos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Max. Paramedicos", "Max. Ambulancias", "Ranking"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabla_complejos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_complejosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla_complejos);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Complejos Hospitalarios");

        javax.swing.GroupLayout ComplejosListarLayout = new javax.swing.GroupLayout(ComplejosListar.getContentPane());
        ComplejosListar.getContentPane().setLayout(ComplejosListarLayout);
        ComplejosListarLayout.setHorizontalGroup(
            ComplejosListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComplejosListarLayout.createSequentialGroup()
                .addGroup(ComplejosListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComplejosListarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ComplejosListarLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel7)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        ComplejosListarLayout.setVerticalGroup(
            ComplejosListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComplejosListarLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel7)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        Eliminar_complejos.setText("Eliminar");
        Eliminar_complejos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_complejosActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Eliminar_complejos);

        Tabla_ambulancias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Año", "Velocidad", "Complejo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tabla_ambulancias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_ambulanciasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Tabla_ambulancias);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("Ambulancias");

        javax.swing.GroupLayout AmbulanciaListarLayout = new javax.swing.GroupLayout(AmbulanciaListar.getContentPane());
        AmbulanciaListar.getContentPane().setLayout(AmbulanciaListarLayout);
        AmbulanciaListarLayout.setHorizontalGroup(
            AmbulanciaListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AmbulanciaListarLayout.createSequentialGroup()
                .addGroup(AmbulanciaListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AmbulanciaListarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AmbulanciaListarLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel20)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        AmbulanciaListarLayout.setVerticalGroup(
            AmbulanciaListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AmbulanciaListarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPopupMenu2.add(Eliminar);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("Reasignacion");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Paramedicos");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Ambulancias");

        jButton13.setText("Reasignar");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        jButton14.setText("Reasignar");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ReasignacionLayout = new javax.swing.GroupLayout(Reasignacion.getContentPane());
        Reasignacion.getContentPane().setLayout(ReasignacionLayout);
        ReasignacionLayout.setHorizontalGroup(
            ReasignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReasignacionLayout.createSequentialGroup()
                .addGroup(ReasignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReasignacionLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel21))
                    .addGroup(ReasignacionLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(ReasignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ReasignacionLayout.createSequentialGroup()
                                .addGroup(ReasignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel22))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(ReasignacionLayout.createSequentialGroup()
                                .addGroup(ReasignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cb_reAmbulancias, javax.swing.GroupLayout.Alignment.LEADING, 0, 169, Short.MAX_VALUE)
                                    .addComponent(cb_reParamedicos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(39, 39, 39)
                                .addGroup(ReasignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_reComplejos1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_reComplejos2, 0, 173, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addGroup(ReasignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton14, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(37, 37, 37))
        );
        ReasignacionLayout.setVerticalGroup(
            ReasignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReasignacionLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addGap(43, 43, 43)
                .addGroup(ReasignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_reParamedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_reComplejos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(32, 32, 32)
                .addGroup(ReasignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_reAmbulancias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_reComplejos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14))
                .addGap(53, 53, 53))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Administacion");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 400, 180, 100);

        jButton2.setText("Mapa");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(330, 400, 180, 100);

        jButton3.setText("Emergencias");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(600, 400, 180, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Administracion.setModal(true);
        Administracion.pack();
        Administracion.setLocationRelativeTo(this);
        Administracion.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Mapa.setModal(true);
        Mapa.pack();
        Mapa.setLocationRelativeTo(this);
        Mapa.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Emergencias.setModal(true);
        Emergencias.pack();
        Emergencias.setLocationRelativeTo(this);
        Emergencias.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        Complejos.setModal(true);
        Complejos.pack();
        Complejos.setLocationRelativeTo(this);
        Administracion.setVisible(false);
        Complejos.setVisible(true);
        while (Complejos.isActive() == true) {
            Administracion.setVisible(true);
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < Arraycomplejos.size(); i++) {
            modelo.addElement(((ComplejosHospitalarios) Arraycomplejos.get(i)).getNombreComlejo());
        }
        Cb_hospitales.setModel(modelo);
        Paramedicos.setModal(true);
        Paramedicos.pack();
        Paramedicos.setLocationRelativeTo(this);
        Administracion.setVisible(false);
        Paramedicos.setVisible(true);
        while (Paramedicos.isActive() == true) {
            Administracion.setVisible(true);
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < Arraycomplejos.size(); i++) {
            modelo.addElement(((ComplejosHospitalarios) Arraycomplejos.get(i)).getNombreComlejo());
        }
        Cb_ambulancias.setModel(modelo);
        Ambulancias.setModal(true);
        Ambulancias.pack();
        Ambulancias.setLocationRelativeTo(this);
        Administracion.setVisible(false);
        Ambulancias.setVisible(true);
        while (Ambulancias.isActive() == true) {
            Administracion.setVisible(true);
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        String nombre = t_nombrehospitales.getText();
        String direccion = a_Direccion.getText();
        int maxparamedicos = (int) Sp_paramedicos.getValue();
        int maxambulancias = (int) Sp_ambulancias.getValue();
        char ranking = (char) Cb_rankingHospitales.getSelectedItem().toString().charAt(0);
        int cont = 0;
        for (Object Arraycomplejo : Arraycomplejos) {
            if (((ComplejosHospitalarios) Arraycomplejo).getNombreComlejo().equals(nombre)) {
                cont++;
            }
        }
        if (cont == 0) {
            if (ranking == 'A') {
                ComplejosHospitalarios temp=new ComplejosHospitalarios(nombre, direccion, maxparamedicos, maxambulancias, Ranking.A);
                Arraycomplejos.add(temp);
            } else if (ranking == 'B') {
                ComplejosHospitalarios temp=new ComplejosHospitalarios(nombre, direccion, maxparamedicos, maxambulancias, Ranking.B);
                Arraycomplejos.add(temp);
            } else if (ranking == 'C') {
                ComplejosHospitalarios temp=new ComplejosHospitalarios(nombre, direccion, maxparamedicos, maxambulancias, Ranking.C);
                Arraycomplejos.add(temp);
            } else {
                ComplejosHospitalarios temp=new ComplejosHospitalarios(nombre, direccion, maxparamedicos, maxambulancias, Ranking.D);
                Arraycomplejos.add(temp);
            }
            JOptionPane.showMessageDialog(this.Complejos, "Se ha guardado exitosamente");
            t_nombrehospitales.setText("");
            a_Direccion.setText("");
            Sp_paramedicos.setValue(0);
            Sp_ambulancias.setValue(0);
        } else {
            JOptionPane.showMessageDialog(Complejos, "Ya existe este Complejo Hospitalario");
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        DefaultTableModel modelo = (DefaultTableModel) tabla_complejos.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        for (int i = 0; i < Arraycomplejos.size(); i++) {
            String[] arr = new String[4];
            ComplejosHospitalarios temp = (ComplejosHospitalarios) Arraycomplejos.get(i);
            arr[0] = temp.getNombreComlejo();
            arr[1] = Integer.toString(temp.getMaxParamedicos());
            arr[2] = Integer.toString(temp.getMaxAmbulancias());
            arr[3] = temp.getRank().toString();
            modelo.addRow(arr);
        }
        tabla_complejos.setModel(modelo);
        ComplejosListar.setModal(true);
        ComplejosListar.pack();
        ComplejosListar.setLocationRelativeTo(this);
        Complejos.setVisible(false);
        ComplejosListar.setVisible(true);
        while (ComplejosListar.isActive() == true) {
            Complejos.setVisible(true);
        }

    }//GEN-LAST:event_jButton8MouseClicked

    private void tabla_complejosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_complejosMouseClicked
        if (evt.isMetaDown()) {
            jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tabla_complejosMouseClicked

    private void Eliminar_complejosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_complejosActionPerformed
        int seleccion = tabla_complejos.getSelectedRow();
        if (seleccion != -1) {
            Arraycomplejos.remove(seleccion);
        } else {
            JOptionPane.showMessageDialog(ComplejosListar, "No ha seleccionado bien");
        }
        DefaultTableModel modelo = (DefaultTableModel) tabla_complejos.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        for (int i = 0; i < Arraycomplejos.size(); i++) {
            String[] arr = new String[4];
            ComplejosHospitalarios temp = (ComplejosHospitalarios) Arraycomplejos.get(i);
            arr[0] = temp.getNombreComlejo();
            arr[1] = Integer.toString(temp.getMaxParamedicos());
            arr[2] = Integer.toString(temp.getMaxAmbulancias());
            arr[3] = temp.getRank().toString();
            modelo.addRow(arr);
        }
        tabla_complejos.setModel(modelo);
    }//GEN-LAST:event_Eliminar_complejosActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        String nombre = t_nombreParamedico.getText();
        int edad = (int) Sp_edad.getValue();
        String id = t_id.getText();
        char ranking = (char) Cb_rankingParamedicos.getSelectedItem().toString().charAt(0);
        int cont = 0;
        int index = Cb_hospitales.getSelectedIndex();
        String complejo = Cb_hospitales.getSelectedItem().toString();
        int limite = 0;
        int sizearray = 0;
        for (int i = 0; i < Arraycomplejos.size(); i++) {
            if (((ComplejosHospitalarios) Arraycomplejos.get(i)).getNombreComlejo().equals(complejo)) {
                limite = ((ComplejosHospitalarios) Arraycomplejos.get(i)).getMaxParamedicos();
                sizearray = ((ComplejosHospitalarios) Arraycomplejos.get(i)).getParamedicos().size();
            }
        }
        for (Object Arrayparamedico : Arrayparamedicos) {
            if (((Paramedicos) Arrayparamedico).getID().equals(id)) {
                cont++;
            }
        }
        if (sizearray < limite) {
            if (cont == 0) {
                if (ranking == 'A') {
                    Paramedicos temp = new Paramedicos(nombre, edad, id, Ranking.A, complejo);
                    Arrayparamedicos.add(temp);
                    ((ComplejosHospitalarios) Arraycomplejos.get(index)).getParamedicos().add(temp);
                } else if (ranking == 'B') {
                    Paramedicos temp = new Paramedicos(nombre, edad, id, Ranking.B, complejo);
                    Arrayparamedicos.add(temp);
                    ((ComplejosHospitalarios) Arraycomplejos.get(index)).getParamedicos().add(temp);
                } else if (ranking == 'C') {
                    Paramedicos temp = new Paramedicos(nombre, edad, id, Ranking.C, complejo);
                    Arrayparamedicos.add(temp);
                    ((ComplejosHospitalarios) Arraycomplejos.get(index)).getParamedicos().add(temp);
                } else {
                    Paramedicos temp = new Paramedicos(nombre, edad, id, Ranking.D, complejo);
                    Arrayparamedicos.add(temp);
                    ((ComplejosHospitalarios) Arraycomplejos.get(index)).getParamedicos().add(temp);
                }
                JOptionPane.showMessageDialog(Paramedicos, "Se ha guardado exitosamente");
                t_nombreParamedico.setText("");
                t_id.setText("");
                Sp_edad.setValue(0);
            } else {
                JOptionPane.showMessageDialog(Paramedicos, "Ya existe este Paramedico");
            }
        } else {
            JOptionPane.showMessageDialog(Paramedicos, "Ya no se pueden agregar mas paramedicos al Complejo Hospitalario seleccionado");
        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        try {
            String placa = t_placa.getText();
            int ano = Integer.parseInt(t_ano.getText());
            int velocidad = Integer.parseInt(t_velocidad.getText());
            int cont = 0;
            int index = Cb_ambulancias.getSelectedIndex();
            String complejo = Cb_ambulancias.getSelectedItem().toString();
            for (Object ArrayAmbulancia : Arrayambulancias) {
                if (((Ambulancia) ArrayAmbulancia).getNumeroPlaca().equals(placa)) {
                    cont++;
                }
            }
            int limite = 0;
            int sizearray = 0;
            for (int i = 0; i < Arraycomplejos.size(); i++) {
                if (((ComplejosHospitalarios) Arraycomplejos.get(i)).getNombreComlejo().equals(complejo)) {
                    limite = ((ComplejosHospitalarios) Arraycomplejos.get(i)).getMaxAmbulancias();
                    sizearray = ((ComplejosHospitalarios) Arraycomplejos.get(i)).getAmbulancias().size();
                }
            }
            if (sizearray < limite) {
                if (cont == 0) {
                    Ambulancia temp = new Ambulancia(placa, ano, velocidad, complejo);
                    Arrayambulancias.add(temp);
                    ((ComplejosHospitalarios) Arraycomplejos.get(index)).getAmbulancias().add(temp);
                    JOptionPane.showMessageDialog(Ambulancias, "Se ha guardado exitosamente");
                    t_placa.setText("");
                    t_ano.setText("");
                    t_velocidad.setText("");
                } else {
                    JOptionPane.showMessageDialog(Ambulancias, "Ya existe esta ambulancia");
                }
            } else {
                JOptionPane.showMessageDialog(Ambulancias, "Ya no se pueden agregar mas ambulancias al Complejo Hospitalario seleccionado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(Ambulancias, "Algun dato ingresado erroneamente");
        }
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        DefaultTableModel modelo = (DefaultTableModel) Tabla_ambulancias.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        for (int i = 0; i < Arrayambulancias.size(); i++) {
            String[] arr = new String[4];
            Ambulancia temp = (Ambulancia) Arrayambulancias.get(i);
            arr[0] = temp.getNumeroPlaca();
            arr[1] = Integer.toString(temp.getYear());
            arr[2] = Integer.toString(temp.getVelocidad());
            arr[3] = temp.getComplejoHospitalario();
            modelo.addRow(arr);
        }
        Tabla_ambulancias.setModel(modelo);
        AmbulanciaListar.setModal(true);
        AmbulanciaListar.pack();
        AmbulanciaListar.setLocationRelativeTo(this);
        Ambulancias.setVisible(false);
        AmbulanciaListar.setVisible(true);
        while (AmbulanciaListar.isActive() == true) {
            Ambulancias.setVisible(true);
        }
    }//GEN-LAST:event_jButton12MouseClicked

    private void Tabla_ambulanciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_ambulanciasMouseClicked
        if (evt.isMetaDown()) {
            jPopupMenu2.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_Tabla_ambulanciasMouseClicked

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        int seleccion = Tabla_ambulancias.getSelectedRow();
        Ambulancia temp = ((Ambulancia) Arrayambulancias.get(seleccion));
        if (seleccion != -1) {
            for (int i = 0; i < Arraycomplejos.size(); i++) {
                if (((ComplejosHospitalarios) Arraycomplejos.get(i)).getNombreComlejo().equals(temp.getComplejoHospitalario())) {
                    for (int j = 0; j < ((ComplejosHospitalarios) Arraycomplejos.get(i)).getAmbulancias().size(); j++) {
                        if (((ComplejosHospitalarios) Arraycomplejos.get(i)).getAmbulancias().get(j).getNumeroPlaca().equals(temp.getNumeroPlaca())) {
                            ((ComplejosHospitalarios) Arraycomplejos.get(i)).getAmbulancias().remove(j);
                        }
                    }
                }
            }
            Arrayambulancias.remove(seleccion);
        } else {
            JOptionPane.showMessageDialog(ComplejosListar, "No ha seleccionado bien");
        }
        DefaultTableModel modelo = (DefaultTableModel) Tabla_ambulancias.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        for (int i = 0; i < Arrayambulancias.size(); i++) {
            String[] arr = new String[4];
            Ambulancia temp1 = (Ambulancia) Arrayambulancias.get(i);
            arr[0] = temp1.getNumeroPlaca();
            arr[1] = Integer.toString(temp1.getYear());
            arr[2] = Integer.toString(temp1.getVelocidad());
            arr[3] = temp1.getComplejoHospitalario();
            modelo.addRow(arr);
        }
        Tabla_ambulancias.setModel(modelo);
    }//GEN-LAST:event_EliminarActionPerformed

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < Arraycomplejos.size(); i++) {
            modelo.addElement(((ComplejosHospitalarios) Arraycomplejos.get(i)).getNombreComlejo());
        }
        cb_reComplejos1.setModel(modelo);
        cb_reComplejos2.setModel(modelo);
        DefaultComboBoxModel modelo1 = new DefaultComboBoxModel();
        for (int i = 0; i < Arrayparamedicos.size(); i++) {
            modelo1.addElement(((Paramedicos) Arrayparamedicos.get(i)).getNombreParamedico());
        }
        cb_reParamedicos.setModel(modelo1);
        DefaultComboBoxModel modelo2 = new DefaultComboBoxModel();
        for (int i = 0; i < Arrayambulancias.size(); i++) {
            modelo2.addElement(((Ambulancia) Arrayambulancias.get(i)).getNumeroPlaca());
        }
        cb_reAmbulancias.setModel(modelo2);
        Reasignacion.setModal(true);
        Reasignacion.pack();
        Reasignacion.setLocationRelativeTo(this);
        Administracion.setVisible(false);
        Reasignacion.setVisible(true);
        while (Reasignacion.isActive() == true) {
            Administracion.setVisible(true);
        }
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        String complejo = cb_reComplejos1.getSelectedItem().toString();
        String medico = cb_reParamedicos.getSelectedItem().toString();
        for (int i = 0; i < Arrayparamedicos.size(); i++) {
            if (((Paramedicos)Arrayparamedicos.get(i)).getNombreParamedico().equals(medico)) {
                ((Paramedicos)Arrayparamedicos.get(i)).setComplejoHospitalario(complejo);
            }
        }
        for (int i = 0; i < Arraycomplejos.size(); i++) {
            PriorityQueue<Paramedicos> temp=new PriorityQueue();
            for (int j = 0; j < Arrayparamedicos.size(); j++) {
                if (((ComplejosHospitalarios)Arraycomplejos.get(i)).getNombreComlejo().equals(((Paramedicos)Arrayparamedicos.get(j)).getComplejoHospitalario())) {
                    temp.add((Paramedicos)Arrayparamedicos.get(j));
                }
            }
            ((ComplejosHospitalarios)Arraycomplejos.get(i)).setParamedicos(temp);
        }
        JOptionPane.showMessageDialog(Reasignacion, "Se ha efectuado el cambio exitosamente");        
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        String complejo = cb_reComplejos2.getSelectedItem().toString();
        String placa = cb_reAmbulancias.getSelectedItem().toString();
        for (int i = 0; i < Arrayambulancias.size(); i++) {
            if (((Ambulancia)Arrayambulancias.get(i)).getNumeroPlaca().equals(placa)) {
                ((Ambulancia)Arrayambulancias.get(i)).setComplejoHospitalario(complejo);
            }
        }
        for (int i = 0; i < Arraycomplejos.size(); i++) {
            ArrayList<Ambulancia> temp= new ArrayList();
            for (int j = 0; j < Arrayambulancias.size(); j++) {
                if (((ComplejosHospitalarios)Arraycomplejos.get(i)).getNombreComlejo().equals(((Ambulancia)Arrayambulancias.get(j)).getComplejoHospitalario())) {
                    temp.add((Ambulancia)Arrayambulancias.get(j));
                }
            }
            ((ComplejosHospitalarios)Arraycomplejos.get(i)).setAmbulancias(temp);
        }
        JOptionPane.showMessageDialog(Reasignacion, "Se ha efectuado el cambio exitosamente");
    }//GEN-LAST:event_jButton14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Administracion;
    private javax.swing.JDialog AmbulanciaListar;
    private javax.swing.JDialog Ambulancias;
    private javax.swing.JComboBox Cb_ambulancias;
    private javax.swing.JComboBox Cb_hospitales;
    private javax.swing.JComboBox Cb_rankingHospitales;
    private javax.swing.JComboBox Cb_rankingParamedicos;
    private javax.swing.JDialog Complejos;
    private javax.swing.JDialog ComplejosListar;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Eliminar_complejos;
    private javax.swing.JDialog Emergencias;
    private javax.swing.JDialog Mapa;
    private javax.swing.JDialog Paramedicos;
    private javax.swing.JDialog Reasignacion;
    private javax.swing.JSpinner Sp_ambulancias;
    private javax.swing.JSpinner Sp_edad;
    private javax.swing.JSpinner Sp_paramedicos;
    private javax.swing.JTable Tabla_ambulancias;
    private javax.swing.JTextArea a_Direccion;
    private javax.swing.JComboBox cb_reAmbulancias;
    private javax.swing.JComboBox cb_reComplejos1;
    private javax.swing.JComboBox cb_reComplejos2;
    private javax.swing.JComboBox cb_reParamedicos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField t_ano;
    private javax.swing.JTextField t_id;
    private javax.swing.JTextField t_nombreParamedico;
    private javax.swing.JTextField t_nombrehospitales;
    private javax.swing.JTextField t_placa;
    private javax.swing.JTextField t_velocidad;
    private javax.swing.JTable tabla_complejos;
    // End of variables declaration//GEN-END:variables
    ArrayList Arraycomplejos = new ArrayList();
    ArrayList Arrayparamedicos = new ArrayList();
    ArrayList Arrayambulancias = new ArrayList();

}
